create database projeto;
use projeto;
create table USUARIO(
	ID integer primary key auto_increment,
    LOGIN varchar(200) unique key,
    SENHA varchar(200),
    GENERO varchar(20),
    IDADE varchar (20)
);


CREATE TABLE JOGO ( 
COD_FINAL INT,
NOME VARCHAR (30),
CONSTRAINT JOGO_PK PRIMARY KEY (COD_FINAL)
);

CREATE TABLE CONSULTA( 
 ID_FK integer,
 COD_FINAL INT, 
 COD_FINAL_FK VARCHAR (50),
 DT_PARTIDA VARCHAR (50),
 CONSTRAINT CONSULTA_PK PRIMARY KEY (ID_FK, COD_FINAL_FK),
CONSTRAINT USUARIO_FK FOREIGN KEY (ID_FK) REFERENCES USUARIO (ID),
CONSTRAINT JOGO_FK FOREIGN KEY (COD_FINAL_FK) REFERENCES JOGO (COD_FINAL)
);

CREATE TABLE FEEDBACK (
ID_FK INTEGER,
COD_FINAL_FK INT,
DT_OPINIAO VARCHAR (30),
ESTRELAS INT,
CONSTRAINT FEEDBACK_PK PRIMARY KEY (ID_FK, COD_FINAL_FK),
CONSTRAINT USUARIO_FK FOREIGN KEY (ID_FK) REFERENCES USUARIO (ID),
CONSTRAINT JOGO_FK FOREIGN KEY (COD_FINAL_FK) REFERENCES JOGO (COD_FINAL)
);

CREATE TABLE OPINIOES(
OPINIOO TEXT, 
DT_OPINIAO DATE,
ID_USU_FK int,
CONSTRAINT USUARIO_FK foreign key (ID_USU_FK) REFERENCES USUARIO (ID)
);
select * from usuario;
INSERT INTO OPINIOES values('ALOALO',1);

select * from opinioes;


